### ISSUE TITLE
It should be very easy to get logs from the app in case of issues

### ISSUE THREAD

**Issue by okdistribute** [getditto/demoapp-skyservice#38]
## Problem

When issues occur, it is challenging to get logs from end-users to quickly diagnose problems and create engineering tickets. Demo apps like skyservice, chat, and inventory are key tools to find out problems early in the development cycle of Ditto.

## Solution

* What is the process to easily get logs? We should document this in a notion doc for testers and sales folks.
* Is there any code that needs to change across apps to make the process easier?
* Do we want to integrate things like @magicwave 's work: https://github.com/getditto/swift-ditto-logs
* Should we default to debug level in the demo apps?

**Comment by texasRanger09** [comment]
It looks like https://github.com/getditto/swift-ditto-logs shows an example of how you can export your logs from xcode rather than the UI of the app like you can with https://github.com/getditto/DittoSwiftTools/tree/main/Sources/DittoExportLogs. For sales folks it would be easier for us to use the DittoSwiftTools-ExportLogs in our demo apps since sales wont have xcode.

**Comment by okdistribute** [comment]
Yeah export logs makes sense!

**Comment by texasRanger09** [comment]
ExportLogs are added from the DittoSwiftTools library. Closing issue.
